### ISSUE TITLE
GRIT data source wrong

### ISSUE THREAD

**Issue by M3Dade** [williamium3000/awesome-mllm-grounding#1]
> We introduce GRIT, a large-scale dataset of Grounded Image-Text pairs, which is created based on image-text pairs from a subset of COYO-700M [BPK+22] and LAION-2B [SBV+22]).
![image](https://github.com/user-attachments/assets/b3e42621-a66a-46c7-8efe-9e124968b548)

**Comment by williamium3000** [comment]
pr accepted. Thanks for pointing out!
